name: Send Email on Commit

on:
  push:
    branches:
      - '**'

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: actions/send-email@v1
        with:
          to: ${{ secrets.EMAIL_TO }}
          subject: Commit Notification
          body: |
            A new commit has been made to the repository on branch ${{ github.event.ref }}.
